services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: analytics-api:v1
    env_file:
      - .env.compose
    ports:
      - "8002:8002"
    volumes:
      - ./src:/code:rw

  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: time-user
      POSTGRES_PASSWORD: time-pw
      POSTGRES_DB: timescaledb
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data:
